### ISSUE TITLE
About pedestrian distance visualization

### ISSUE THREAD

**Issue by 1074727076** [DrMahdiRezaei/DeepSOCIAL#2]
hi, what method is used to realize pedestrian distance visualization ，I tried it with python but the effect is not  good

**Comment by DrMahdiRezaei** [comment]
Hi there,

For distance estimation, you need to perform inverse perspective mapping followed by camera calibration for your videos. The provided code is calibrated for the Oxford dataset.
Hope that helps.

________________________________
From: hyccc ***@***.***>
Sent: 13 July 2021 07:35
To: DrMahdiRezaei/DeepSOCIAL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DrMahdiRezaei/DeepSOCIAL] About pedestrian distance visualization (#2)


hi, what method is used to realize pedestrian distance visualization ，I tried it with python but the effect is not good

**Comment by 1074727076** [comment]
thanks for your answer it is very helpful for me! I still have a question: how to make Mosaic heat map？The heat map I made doesn't look good  hahaha
