### ISSUE TITLE
Question about the Label file of Oxford Town Dataset

### ISSUE THREAD

**Issue by gujiaqivadin** [DrMahdiRezaei/DeepSOCIAL#3]
Hello, Dr.MahdiRezaei!
  Thanks for sharing your method. I am wondering whether there is people's 3d groundtruth location labels for your provided Oxford Town Dataset.

**Comment by DrMahdiRezaei** [comment]
Dear Jiaqi,

Thank you for your interest.
Unfortunately, we do not have the 3D ground truth label for the Oxford Dataset,

All the best,

Mahdi


________________________________
From: Jiaqi Gu ***@***.***>
Sent: 25 July 2021 16:33
To: DrMahdiRezaei/DeepSOCIAL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DrMahdiRezaei/DeepSOCIAL] Question about the Label file of Oxford Town Dataset (#3)


Hello, Dr.MahdiRezaei!
Thanks for sharing your method. I am wondering whether there is people's 3d groundtruth location labels for your provided Oxford Town Dataset.
