### ISSUE TITLE
There is magic number error

### ISSUE THREAD

**Issue by Jasolicon** [DrMahdiRezaei/DeepSOCIAL#5]
When I run the code on VSCode ,I got error as "ImportError: bad magic number in 'deepsocial': b'B\r\r\n'" and I coundn't deal with it. May I ask for the original code of deppsocial.py or any other solutions? Thank you very much

**Comment by DrMahdiRezaei** [comment]
Hi Jasolicon,
The magic number comes from Unix-type systems where the first few bytes of a file hold a marker indicating the file type. Anything that damages this magic number leads to such a problem. This includes editing the .pyc file or trying to run a .pyc from a different version of python (usually newer versions than your interpreter). Please download and use the deepsocial.pyc file and make sure that your python version is 3.7.7 64-bit.
