### ISSUE TITLE
透视变换的dst

### ISSUE THREAD

**Issue by Deepcong2019** [DrMahdiRezaei/DeepSOCIAL#8]
calibration      = [[180,162],[618,0],[552,540],[682,464]]
这个为什么这样取值啊，冒昧问一下。

**Comment by DrMahdiRezaei** [comment]
??!

**Comment by Deepcong2019** [comment]
> ??!

用opencv求 透视矩阵的时候，，这个对应的4个测量点的坐标  为什么这样取值啊，，论文和代码里边  好像都没说 这四个点的来源

**Comment by DrMahdiRezaei** [comment]
Cant you write in English? I am not Chinese! I will close it. Sorry.

**Comment by Deepcong2019** [comment]
I'm so sorry. Why do the four measurement coordinates take this value when using OpenCV to calculate the perspective matrix? As follows：
calibration = [[180,162],[618,0],[552,540],[682,464]]

**Comment by DrMahdiRezaei** [comment]
These coordinates represent the four corners of the bird's eye view image that corresponds to the locations of the same pixels in the perspective image.

**Comment by 133213** [comment]
How do you calculate the four coordinates

**Comment by DrMahdiRezaei** [comment]
They are the results of transforming the four corners of the perspective image (CCTV camera) to their real-world corresponding points on the estimated ground plane (where Z=0), provided by the OTC dataset camera calibration information.
